
name: training_memo
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+4
#リリース時変更

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+9
  provider: ^4.3.2+3
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.2+1
  cupertino_icons: ^1.0.0
  google_sign_in: ^4.5.6
  intl: ^0.16.1
  flutter_signin_button: ^1.1.0
  gradient_app_bar: ^0.0.1
  numberpicker: ^1.3.0
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^0.2.9


flutter:
  uses-material-design: true
  assets:
    - lib/assets/icon.jpg

module:
  androidX: true


flutter_icons:
  image_path: "lib/assets/icon.jpg"
  android: true
  ios: true

flutter_native_splash:
  image: "lib/assets/icon.png"
  color: "#FFFFFF"